wandb_version: 1

weights:
  desc: null
  value: ''
cfg:
  desc: null
  value: models\resnet10.yaml
data:
  desc: null
  value: data\bdd100k.yaml
hyp:
  desc: null
  value:
    lr0: 0.01
    lrf: 0.1
    momentum: 0.937
    weight_decay: 0.0005
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    warmup_bias_lr: 0.1
    box: 0.05
    cls: 0.5
    cls_pw: 1.0
    obj: 1.0
    obj_pw: 1.0
    iou_t: 0.2
    anchor_t: 4.0
    fl_gamma: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    degrees: 0.0
    translate: 0.1
    scale: 0.5
    shear: 0.0
    perspective: 0.0
    flipud: 0.0
    fliplr: 0.5
    mosaic: 1.0
    mixup: 0.0
    copy_paste: 0.0
    slide_ratio: 0.0
epochs:
  desc: null
  value: 300
batch_size:
  desc: null
  value: 16
imgsz:
  desc: null
  value: 640
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
nosave:
  desc: null
  value: false
noval:
  desc: null
  value: false
noautoanchor:
  desc: null
  value: false
evolve:
  desc: null
  value: null
bucket:
  desc: null
  value: ''
cache:
  desc: null
  value: null
image_weights:
  desc: null
  value: false
device:
  desc: null
  value: ''
multi_scale:
  desc: null
  value: false
single_cls:
  desc: null
  value: false
adam:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
workers:
  desc: null
  value: 8
project:
  desc: null
  value: runs\train
name:
  desc: null
  value: exp
exist_ok:
  desc: null
  value: false
quad:
  desc: null
  value: false
linear_lr:
  desc: null
  value: false
label_smoothing:
  desc: null
  value: 0.0
patience:
  desc: null
  value: 100
freeze:
  desc: null
  value: 0
save_period:
  desc: null
  value: -1
local_rank:
  desc: null
  value: -1
entity:
  desc: null
  value: null
upload_dataset:
  desc: null
  value: false
bbox_interval:
  desc: null
  value: -1
artifact_alias:
  desc: null
  value: latest
cupy:
  desc: null
  value: true
noplots:
  desc: null
  value: false
save_dir:
  desc: null
  value: runs\train\exp28
_wandb:
  desc: null
  value:
    bounding_box/class_labels:
      BoundingBoxDebugger_wandb_delimeter_predictions:
        type: bounding_box/class_labels
        key: BoundingBoxDebugger_wandb_delimeter_predictions
        value:
          '0': person
          '1': rider
          '2': car
          '3': bus
          '4': truck
          '5': bike
          '6': motor
          '7': tl_green
          '8': tl_red
          '9': tl_yellow
          '10': tl_none
          '11': t_sign
          '12': train
    python_version: 3.8.13
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716209884.452213
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 80
      3:
      - 16
      - 23
      4: 3.8.13
      5: 0.16.3
      8:
      - 3
      - 5
      13: windows-amd64
data_dict:
  desc: null
  value:
    train: bdd100k\train.txt
    val: bdd100k\val.txt
    test: bdd100k\test.txt
    nc: 13
    names:
    - person
    - rider
    - car
    - bus
    - truck
    - bike
    - motor
    - tl_green
    - tl_red
    - tl_yellow
    - tl_none
    - t_sign
    - train
